version: '3'

services:
  flaskapp:
    image: iceguy/jadzia-flask:alpha
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_RUN_HOST: '0.0.0.0'
  
  celeryworker:
    image: iceguy/jadzia-celery:alpha
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

