apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: celeryworker
  name: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celeryworker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: celeryworker
    spec:
      containers:
        - image: iceguy/jadzia-celery:alpha
          name: celeryworker
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: celeryworker-claim0
      restartPolicy: Always
      volumes:
        - name: celeryworker-claim0
          persistentVolumeClaim:
            claimName: celeryworker-claim0
status: {}
