apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: flaskapp
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flaskapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: flaskapp
    spec:
      containers:
        - env:
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
          image: iceguy/jadzia-flask:alpha
          name: flaskapp
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: flaskapp-claim0
      restartPolicy: Always
      volumes:
        - name: flaskapp-claim0
          persistentVolumeClaim:
            claimName: flaskapp-claim0
status: {}
